spring:
  application:
    name: spring-cloud-zipkin

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#zipkin 2.10后的配置
management:
  metrics:
    web:
      server:
        auto-time-requests: false